### PR TITLE
Shortened the Intro para and corrected some grammar.

### PR DESCRIPTION
**Pull request by ranbir7**

### CODE REVIEW

**Comment by ranbir7** [comment]
what is making the tests fail though? Really confused Right now.

**Comment by ConnorStoneAstro** [comment]
Sorry about the failing tests, that is an issue on my end, not you. I am currently working with GitHub support to fix it. For some reason the testing code is running partially on an old branch. Your modifications look great! I'll approve the PR once I have the testing bug sorted out.

**Comment by ConnorStoneAstro** [comment]
Ok, the bug is more complex than expected. I have reverted the changes on the main branch and I'll continue working on the dev branch (you don't need to worry about it). So the man branch now works properly. Can you pull the latest version of main to your fork and submit a new commit. Everything should work now. Sorry for the inconvenience!

**Comment by ranbir7** [comment]
lemme see if it works

**Pull request closed without merging**
