### PR TITLE
Updated after revert changes

### PR DESCRIPTION
**Pull request by ranbir7**

### CODE REVIEW

**Comment by ConnorStoneAstro** [comment]
Hi Ranbir, I'm not sure why the checks are failing. As you can see, the checks for the main branch run properly, and all you changed was the readme file so it should be ok. I think the GitHub server cached a bad copy of the code. Hopefully they can fix it

**Comment by ConnorStoneAstro** [comment]
At this point it's not clear what can be done. You could try forking the repo again and starting fresh maybe?

**Comment by ConnorStoneAstro** [comment]
oh, looks like its working now!

**Review by ConnorStoneAstro — APPROVED** [review]
Looks good!

**Comment by ranbir7** [comment]
Glad it worked 🥴

**Pull request merged**
